### ISSUE TITLE
Copying/moving splines is dangerous

### ISSUE THREAD

**Issue by AlexRockliff** [NCAR/bspline#3]
BSpline<T> and BSplineBase<T> have destructors defined, but do not have all copy/move/assignment operators defined.
Putting splines into a container that may choose to copy them therefore is dangerous, as copying a BSpline will leave the copy with a deleted spline if the original spline object goes out of scope.

Refer to this:
https://en.cppreference.com/w/cpp/language/rule_of_three

I suggest replacing the use of raw pointers for BSplineBase<T>::base and BSpline<T>::s with std::unique_ptr, and then defining copy and move constructors and assignment operators. Any operator not explicitly defined would then be implicitly deleted as a result of holding a std::unique_ptr, so a compile time error would be generated for unsupported copy/move/assignment operations instead of a runtime segfault/access violation.

**Comment by garyjg** [comment]
Thanks for pointing that out.  I don't know how I forgot it or how no compiler warnings ever caught it, but I think it's fixed now.  I'll wait to close this until after I add some tests to confirm that the output hasn't changed.

**Comment by garyjg** [comment]
Fixed in v2.1.
